language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn build
  - echo $GITHUB_TOKEN
before_deploy:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: src/.vuepress/dist
  github_token: $GITHUB_TOKEN # defined in travis
  keep_history: true
  target_branch : master
  on:
    branch: vuepress